name: Test ACI

on: [pull_request, workflow_dispatch]

run-name: Test ACI

jobs:

  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install pandas matplotlib pysam
        
      - name: Run ACI
        run: ./aci/aci.py -b test/test.bam -d test/test.bed -o testing

      - name: Run ACI version
        run: ./aci/aci.py -v
      
      - name: Run ACI help
        run: ./aci/aci.py -h

      - name : Final tree
        run: tree .
