name: Test ACI

on: [pull_request, workflow_dispatch]

run-name: Test ACI

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: pip install .
        
      - name: Run ACI
        run: aci -b tests/data/test.bam -d tests/data/test.bed -o testing

      - name: Run ACI version
        run: aci -v
      
      - name: Run ACI help
        run: aci -h

      - name : Final tree
        run: tree .

      - name : Check final files
        run: ls testing/{amplicon_depth.csv,amplicon_depth.png,amplicon_depth_*.bam.png,amplicon_min_depth.csv,amplicon_min_depth.png,overall_depth.csv,*_depth.png}
